server.port=8080


spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER_SERIVICE
sping.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[].id=car-service
spring.cloud.gateway.routes[].uri=lb://CAR-SERVICE
spring.cloud.gateway.routes[].predicates[0]=Path=/cars/**

spring.cloud.gateway.routes[].id=booking-service
spring.cloud.gateway.routes[].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[].predicates[0]=Path=/booking/**

spring.cloud.gateway.routes[].id=auth-service
spring.cloud.gateway.routes[].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[].id=washer-service
spring.cloud.gateway.routes[].uri=lb://WASHER-SERVICE
spring.cloud.gateway.routes[].predicates[0]=Path=/washer/**

spring.cloud.gateway.routes[].id=payment-service
spring.cloud.gateway.routes[].uri=lb://PAYMENT-SEVICE
spring.cloud.gateway.routes[].predicates[0]=Path=/payment/**
